#############################################################################
# Makefile for building: output/Neutron3D
# Generated by qmake (2.01a) (Qt 4.4.3) on: ter fev 17 10:16:58 2009
# Project:  Neutron3D.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile Neutron3D.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Iui -Iui -Itemp/moc -I.
LINK          = g++
LFLAGS        = -Wl,--no-undefined
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = temp/obj/

####### Files

SOURCES       = ui/KeyboardMapping.cpp \
		ui/ProjectManager.cpp \
		ui/About.cpp \
		Main.cpp \
		Application.cpp \
		MainWindow.cpp \
		Preferences.cpp temp/moc/moc_KeyboardMapping.cpp \
		temp/moc/moc_ProjectManager.cpp \
		temp/moc/moc_About.cpp \
		temp/moc/moc_Application.cpp \
		temp/moc/moc_MainWindow.cpp \
		temp/moc/moc_Preferences.cpp
OBJECTS       = temp/obj/KeyboardMapping.o \
		temp/obj/ProjectManager.o \
		temp/obj/About.o \
		temp/obj/Main.o \
		temp/obj/Application.o \
		temp/obj/MainWindow.o \
		temp/obj/Preferences.o \
		temp/obj/moc_KeyboardMapping.o \
		temp/obj/moc_ProjectManager.o \
		temp/obj/moc_About.o \
		temp/obj/moc_Application.o \
		temp/obj/moc_MainWindow.o \
		temp/obj/moc_Preferences.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		ui/Ui.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		Neutron3D.pro
QMAKE_TARGET  = Neutron3D
DESTDIR       = output/
TARGET        = output/Neutron3D

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_KeyboardMapping.h ui_ProjectManager.h ui_About.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) output/ || $(MKDIR) output/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Neutron3D.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		ui/Ui.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile Neutron3D.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
ui/Ui.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Neutron3D.pro

dist: 
	@$(CHK_DIR_EXISTS) temp/obj/Neutron3D1.0.0 || $(MKDIR) temp/obj/Neutron3D1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) temp/obj/Neutron3D1.0.0/ && $(COPY_FILE) --parents ui/KeyboardMapping.h ui/ProjectManager.h ui/About.h Application.h MainWindow.h Preferences.h temp/obj/Neutron3D1.0.0/ && $(COPY_FILE) --parents ui/KeyboardMapping.cpp ui/ProjectManager.cpp ui/About.cpp Main.cpp Application.cpp MainWindow.cpp Preferences.cpp temp/obj/Neutron3D1.0.0/ && $(COPY_FILE) --parents ui/KeyboardMapping.ui ui/ProjectManager.ui ui/About.ui temp/obj/Neutron3D1.0.0/ && (cd `dirname temp/obj/Neutron3D1.0.0` && $(TAR) Neutron3D1.0.0.tar Neutron3D1.0.0 && $(COMPRESS) Neutron3D1.0.0.tar) && $(MOVE) `dirname temp/obj/Neutron3D1.0.0`/Neutron3D1.0.0.tar.gz . && $(DEL_FILE) -r temp/obj/Neutron3D1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: temp/moc/moc_KeyboardMapping.cpp temp/moc/moc_ProjectManager.cpp temp/moc/moc_About.cpp temp/moc/moc_Application.cpp temp/moc/moc_MainWindow.cpp temp/moc/moc_Preferences.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) temp/moc/moc_KeyboardMapping.cpp temp/moc/moc_ProjectManager.cpp temp/moc/moc_About.cpp temp/moc/moc_Application.cpp temp/moc/moc_MainWindow.cpp temp/moc/moc_Preferences.cpp
temp/moc/moc_KeyboardMapping.cpp: ui_KeyboardMapping.h \
		ui/KeyboardMapping.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ui/KeyboardMapping.h -o temp/moc/moc_KeyboardMapping.cpp

temp/moc/moc_ProjectManager.cpp: ui_ProjectManager.h \
		ui/ProjectManager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ui/ProjectManager.h -o temp/moc/moc_ProjectManager.cpp

temp/moc/moc_About.cpp: ui_About.h \
		ui/About.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ui/About.h -o temp/moc/moc_About.cpp

temp/moc/moc_Application.cpp: MainWindow.h \
		ui/KeyboardMapping.h \
		ui_KeyboardMapping.h \
		ui/ProjectManager.h \
		ui_ProjectManager.h \
		ui/About.h \
		ui_About.h \
		Preferences.h \
		Application.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Application.h -o temp/moc/moc_Application.cpp

temp/moc/moc_MainWindow.cpp: ui/KeyboardMapping.h \
		ui_KeyboardMapping.h \
		ui/ProjectManager.h \
		ui_ProjectManager.h \
		ui/About.h \
		ui_About.h \
		Preferences.h \
		MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MainWindow.h -o temp/moc/moc_MainWindow.cpp

temp/moc/moc_Preferences.cpp: Preferences.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Preferences.h -o temp/moc/moc_Preferences.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_KeyboardMapping.h ui_ProjectManager.h ui_About.h
compiler_uic_clean:
	-$(DEL_FILE) ui_KeyboardMapping.h ui_ProjectManager.h ui_About.h
ui_KeyboardMapping.h: ui/KeyboardMapping.ui
	/usr/bin/uic-qt4 ui/KeyboardMapping.ui -o ui_KeyboardMapping.h

ui_ProjectManager.h: ui/ProjectManager.ui
	/usr/bin/uic-qt4 ui/ProjectManager.ui -o ui_ProjectManager.h

ui_About.h: ui/About.ui
	/usr/bin/uic-qt4 ui/About.ui -o ui_About.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

temp/obj/KeyboardMapping.o: ui/KeyboardMapping.cpp ui/KeyboardMapping.h \
		ui_KeyboardMapping.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/KeyboardMapping.o ui/KeyboardMapping.cpp

temp/obj/ProjectManager.o: ui/ProjectManager.cpp ui/ProjectManager.h \
		ui_ProjectManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/ProjectManager.o ui/ProjectManager.cpp

temp/obj/About.o: ui/About.cpp ui/About.h \
		ui_About.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/About.o ui/About.cpp

temp/obj/Main.o: Main.cpp Application.h \
		MainWindow.h \
		ui/KeyboardMapping.h \
		ui_KeyboardMapping.h \
		ui/ProjectManager.h \
		ui_ProjectManager.h \
		ui/About.h \
		ui_About.h \
		Preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/Main.o Main.cpp

temp/obj/Application.o: Application.cpp Application.h \
		MainWindow.h \
		ui/KeyboardMapping.h \
		ui_KeyboardMapping.h \
		ui/ProjectManager.h \
		ui_ProjectManager.h \
		ui/About.h \
		ui_About.h \
		Preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/Application.o Application.cpp

temp/obj/MainWindow.o: MainWindow.cpp MainWindow.h \
		ui/KeyboardMapping.h \
		ui_KeyboardMapping.h \
		ui/ProjectManager.h \
		ui_ProjectManager.h \
		ui/About.h \
		ui_About.h \
		Preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/MainWindow.o MainWindow.cpp

temp/obj/Preferences.o: Preferences.cpp Preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/Preferences.o Preferences.cpp

temp/obj/moc_KeyboardMapping.o: temp/moc/moc_KeyboardMapping.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_KeyboardMapping.o temp/moc/moc_KeyboardMapping.cpp

temp/obj/moc_ProjectManager.o: temp/moc/moc_ProjectManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_ProjectManager.o temp/moc/moc_ProjectManager.cpp

temp/obj/moc_About.o: temp/moc/moc_About.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_About.o temp/moc/moc_About.cpp

temp/obj/moc_Application.o: temp/moc/moc_Application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_Application.o temp/moc/moc_Application.cpp

temp/obj/moc_MainWindow.o: temp/moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_MainWindow.o temp/moc/moc_MainWindow.cpp

temp/obj/moc_Preferences.o: temp/moc/moc_Preferences.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_Preferences.o temp/moc/moc_Preferences.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

